import {
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  Banknote,
  Bold,
  BookOpen,
  Brain,
  BrainCircuit,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  CalendarSync,
  ChartNoAxesColumn,
  ChartNoAxesCombined,
  ChartSpline,
  ChevronDown,
  CircleCheck,
  CircleHelp,
  Clock,
  CloudUpload,
  CreditCard,
  Ellipsis,
  Eye,
  FileChartColumn,
  FileText,
  FileUp,
  FolderArchive,
  Gavel,
  Gift,
  HardHat,
  Headphones,
  House,
  Landmark,
  LayoutGrid,
  ListChecks,
  MailOpen,
  Megaphone,
  Menu,
  MessageCircle,
  NotebookPen,
  Paperclip,
  PiggyBank,
  Plane,
  Plus,
  Receipt,
  ReceiptText,
  RefreshCw,
  Rocket,
  RotateCcw,
  ScanText,
  Search,
  Send,
  SendHorizontal,
  Settings,
  ShieldCheck,
  ShieldPlus,
  ShoppingCart,
  Smile,
  Sparkles,
  SquarePen,
  Store,
  Table2,
  TriangleAlert,
  TrendingUp,
  Utensils,
  Video,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

// Explicit SVG components cannot degrade into visible ligature names when a
// third-party font request is blocked, delayed, or transformed by a CDN.
const ICONS: Record<string, LucideIcon> = {
  account_balance: Landmark,
  add: Plus,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  attach_file: Paperclip,
  auto_awesome: Sparkles,
  bar_chart: ChartNoAxesColumn,
  business_center: BriefcaseBusiness,
  construction: HardHat,
  calendar_today: CalendarDays,
  campaign: Megaphone,
  chat: MessageCircle,
  check: CircleCheck,
  cloud_upload: CloudUpload,
  compare_arrows: ArrowLeftRight,
  credit_card: CreditCard,
  description: FileText,
  document_scanner: ScanText,
  edit_note: NotebookPen,
  edit_square: SquarePen,
  event_repeat: CalendarSync,
  expand_more: ChevronDown,
  fact_check: ListChecks,
  flight: Plane,
  folder_zip: FolderArchive,
  format_bold: Bold,
  forward_to_inbox: MailOpen,
  gavel: Gavel,
  grid_view: LayoutGrid,
  health_and_safety: ShieldPlus,
  headphones: Headphones,
  history: Clock,
  home_work: House,
  insert_chart: ChartNoAxesColumn,
  insights: ChartSpline,
  memory: BrainCircuit,
  menu: Menu,
  menu_book: BookOpen,
  more_horiz: Ellipsis,
  outgoing_mail: Send,
  payments: Banknote,
  psychology: Brain,
  psychology_alt: BrainCircuit,
  query_stats: ChartNoAxesCombined,
  receipt_long: ReceiptText,
  redeem: Gift,
  refresh: RefreshCw,
  report: TriangleAlert,
  request_quote: Receipt,
  restart_alt: RotateCcw,
  rocket_launch: Rocket,
  savings: PiggyBank,
  schedule: Clock,
  schedule_send: SendHorizontal,
  search: Search,
  send: Send,
  sentiment_satisfied: Smile,
  settings: Settings,
  shopping_cart: ShoppingCart,
  storefront: Store,
  summarize: FileChartColumn,
  table_chart: Table2,
  task_alt: CircleCheck,
  trending_up: TrendingUp,
  upload_file: FileUp,
  apartment: Building2,
  restaurant: Utensils,
  verified_user: ShieldCheck,
  videocam: Video,
  visibility: Eye,
};

type MaterialIconProps = Omit<LucideProps, "children"> & {
  name: string;
};

export function MaterialIcon({ name, className, size, strokeWidth, ...props }: MaterialIconProps) {
  const Icon = ICONS[name] ?? CircleHelp;

  return (
    <Icon
      aria-hidden={props["aria-label"] ? undefined : true}
      focusable="false"
      {...props}
      className={["material-symbols-outlined", className].filter(Boolean).join(" ")}
      size={size ?? "1em"}
      strokeWidth={strokeWidth ?? 1.75}
    />
  );
}
